### ISSUE TITLE
Undefined variable: b:undo_ftplugin

### ISSUE THREAD

**Issue by wolfv6** [masukomi/vim-markdown-folding#12]
This error displays at bottom of gVim when I open a markdown file:
Error detected while processing C:\Users\wolf\vimfiles\bundle\vim-markdown-folding\after\ftplugin\markdown\folding.vim
line:20
E121: Undefined variable: b:undo_ftplugin
E121: Undefined variable: b:undo_ftplugin

I press Enter to continue and folding works fine.
I am running Vim 7.4 with Vundle on Windows 7.
This is in my _vimrc file:

set nocompatible
if has("autocmd")
  filetype plugin indent on
endif
Plugin 'nelstrom/vim-markdown-folding'

**Comment by samumist** [comment]
I had the same error code after installed the 'gabrielelana/vim-markdown' plugin. 

I don't like the folding coming with 'gabrielelana/vim-markdown' as it is really a performance hit.
