### ISSUE TITLE
folded areas should not print

### ISSUE THREAD

**Issue by jm3** [masukomi/vim-markdown-folding#23]
When printing from vim (i know, i know, nobody prints, BUT), when there are regions folded and hence hidden, it's unexpected that printing the file should show the folded regions to unfold and appear again.

Any suggestions on how to tackle this in a PR?

**Comment by masukomi** [comment]
Are you trying to print from a GUI client @jm3 ? I think a terminal emulator wouldn't have a clue about what's going on in vim's brain when it goes to print.

MacVim seems to unfold everything for the printed form regardless of filetype. I think the right answer here is to speak with the maintainer of whatever GUI wrapper you use.

**Comment by masukomi** [comment]
Closing this under the assumption that i'm not wrong about this being an issue with the GUI wrapper. Please reopen if I'm wrong.
