### ISSUE TITLE
vspec test runner doesn't conform to recommended style

### ISSUE THREAD

**Issue by nelstrom** [masukomi/vim-markdown-folding#9]
[Follow this guide](http://whileimautomaton.net/2013/02/08211255). [Need vim-markdown to tag a release](https://github.com/tpope/vim-markdown/issues/57) so that this plugin can depend on it.

**Comment by masukomi** [comment]
The `v1.0` release of vim-markdown works if the line is written as 

    flavor 'tpope/vim-markdown', '>= v1.0'

However, with the current version many tests fail. Working on making them pass now.

**Comment by masukomi** [comment]
tests fail with pre-handover version too, just different tests.

**Comment by masukomi** [comment]
all tests are passing now. Minor tweaks to the test file + some changes to support alignment of folded headings from added in 6b2739fcc74cf39a5d9a5e1ac54c94629906e1ed
